@startuml
title
    <img:assets/logos/calypso.svg{scale=0.2}>

    Terminal Calypso Card API 3.0.+ (2026-06-15)
end title

' == THEME (class) ==

'Couleurs issues de : https://htmlcolorcodes.com/fr/tableau-de-couleur/tableau-de-couleur-design-plat/
!define C_GREY1 F8F9F9
!define C_GREY2 F2F3F4
!define C_GREY3 E5E7E9
!define C_GREY4 D7DBDD
!define C_GREY5 CACFD2
!define C_GREY6 BDC3C7
!define C_LINK 3498DB
!define C_USE 27AE60
!define C_THROW 2C3E50

' -- Styles that don't work with new version of plantuml --
skinparam stereotypeABorderColor #A9DCDF
skinparam stereotypeIBorderColor #B4A7E5
skinparam stereotypeCBorderColor #ADD1B2
skinparam stereotypeEBorderColor #EB937F
' -- END --

skinparam ClassBorderThickness 2
skinparam ArrowThickness 2

' Yellow
skinparam ClassBackgroundColor #FEFECE
skinparam ClassBorderColor #D4AC0D
' Red
skinparam ClassBackgroundColor<<red>> #FDEDEC
skinparam ClassBorderColor<<red>> #E74C3C
hide <<red>> stereotype
' Purple
skinparam ClassBackgroundColor<<purple>> #F4ECF7
skinparam ClassBorderColor<<purple>> #8E44AD
hide <<purple>> stereotype
' blue
skinparam ClassBackgroundColor<<blue>> #EBF5FB
skinparam ClassBorderColor<<blue>> #3498DB
hide <<blue>> stereotype
' Green
skinparam ClassBackgroundColor<<green>> #E9F7EF
skinparam ClassBorderColor<<green>> #27AE60
hide <<green>> stereotype
' Grey
skinparam ClassBackgroundColor<<grey>> #EAECEE
skinparam ClassBorderColor<<grey>> #2C3E50
hide <<grey>> stereotype

' == CONTENT ==

legend top
    * __External public API references__
    *** <back:yellow>**Calypsonet Terminal Reader API**</back>
    * __Text__
    *** <color:blue><b>New element added since the last version
    *** <color:red><s><b>Element marked as deprecated since the last version
    *** <s><b>Element marked as deprecated
    *** <color:grey><b>Work in progress...
    * __Object__
    *** <back:#EBF5FB><color:#3498DB><b>Factory or interface provided by the factory
    *** <back:#FEFECE><color:#D4AC0D><b>Interface that cannot be instantiated directly by the factory
    *** <back:#FDEDEC><color:#E74C3C><b>SPI (Service Provider Interface) to be provided by the end-user
    *** <back:#E9F7EF><color:#27AE60><b>Class, enum or error
end legend

package "calypso.card" as calypsoCard {

class "CalypsoCardApiProperties" as ApiProperties <<constants>> <<green>> {
    +const VERSION: String = "3.0"
}
interface "CalypsoCardApiFactory" as CalypsoCardApiFactory <<blue>> {
    +createCalypsoCardSelectionExtension() → CalypsoCardSelectionExtension

    +createSymmetricCryptoSecuritySetting(cryptoCardTransactionManagerFactory: SymmetricCryptoCardTransactionManagerFactory) → SymmetricCryptoSecuritySetting
    +createAsymmetricCryptoSecuritySetting(cryptoCardTransactionManagerFactory: AsymmetricCryptoCardTransactionManagerFactory) → AsymmetricCryptoSecuritySetting

    +createFreeTransactionManager(cardReader: <back:yellow>CardReader</back>, card: CalypsoCard) → FreeTransactionManager
    +createSecureRegularModeTransactionManager(cardReader: <back:yellow>CardReader</back>, card: CalypsoCard, securitySetting: SymmetricCryptoSecuritySetting) → SecureRegularModeTransactionManager
    +createSecureExtendedModeTransactionManager(cardReader: <back:yellow>CardReader</back>, card: CalypsoCard, securitySetting: SymmetricCryptoSecuritySetting) → SecureExtendedModeTransactionManager
    +createSecurePkiModeTransactionManager(cardReader: <back:yellow>CardReader</back>, card: CalypsoCard, securitySetting: AsymmetricCryptoSecuritySetting) → SecurePkiModeTransactionManager

}
enum WriteAccessLevel <<green>> {
    +PERSONALIZATION
    +LOAD
    +DEBIT
}
enum SelectFileControl <<green>> {
    +FIRST_EF
    +NEXT_EF
    +CURRENT_DF
}
enum GetDataTag <<green>> {
    +FCP_FOR_CURRENT_FILE
    +FCI_FOR_CURRENT_DF
    +EF_LIST
    +TRACEABILITY_INFORMATION
    +CARD_PUBLIC_KEY
    +CARD_CERTIFICATE
    +CA_CERTIFICATE
}
enum "PutDataTag" as PutDataTag <<green>> {
    +CARD_KEY_PAIR
    +CARD_CERTIFICATE
    +CA_CERTIFICATE
}
package "card" as card {
    interface "«<back:yellow>CardSelectionExtension</back>»\nCalypsoCardSelectionExtension" as CalypsoCardSelectionExtension <<blue>> {
        +acceptInvalidatedCard() → Self

        +prepareSelectFile(lid: Short) → Self
        +prepareSelectFile(selectControl: SelectFileControl) → Self

        +prepareGetData(tag: GetDataTag) → Self

        +prepareReadRecord(sfi: Byte, recordNumber: Int) → Self
        +prepareReadBinary(sfi: Byte, offset: Int, nbBytesToRead: Int) → Self
        +prepareReadCounter(sfi: Byte, nbCountersToRead: Int) → Self

        +preparePreOpenSecureSession(writeAccessLevel: WriteAccessLevel) → Self
    }
    interface "«<back:yellow>IsoSmartCard</back>»\nCalypsoCard" as CalypsoCard {
        +getProductType() → CalypsoCardProductType
        +isHce() → Boolean

        +isDfInvalidated() → Boolean

        +getDfName() → ByteArray
        +getApplicationSerialNumber() → ByteArray

        +getStartupInfoRawData() → ByteArray
        +getPlatform() → Byte
        +getApplicationType() → Byte
        +getApplicationSubtype() → Byte
        +getSoftwareIssuer() → Byte
        +getSoftwareVersion() → Byte
        +getSoftwareRevision() → Byte
        +getSessionModification() → Byte

        +getTraceabilityInformation() → ByteArray

        +getCardPublicKey() → ByteArray
        +getCardCertificate() → ByteArray
        +getCaCertificate() → ByteArray

        +getDirectoryHeader() → DirectoryHeader?
        +getFileBySfi(sfi: Byte) → ElementaryFile?
        +getFileByLid(lid: Short) → ElementaryFile?
        +getFiles() → Set<ElementaryFile>
        +<color:blue>getCounterValuesBySfi(sfi: Byte) → SortedMap<Int, Int>?
        +<color:blue>getCounterValuesByLid(lid: Short) → SortedMap<Int, Int>?
        +<color:blue>getMatchingRecordNumbers(idCommand: Int) → List<Int>?

        +isDfRatified() → Boolean
        +getTransactionCounter() → Int

        +isPkiModeSupported() → Boolean
        +isExtendedModeSupported() → Boolean
        +isRatificationOnDeselectSupported() → Boolean

        +isPinFeatureAvailable() → Boolean
        +isPinBlocked() → Boolean
        +getPinAttemptRemaining() → Int

        +isSvFeatureAvailable() → Boolean
        +getSvBalance() → Int
        +getSvLastTNum() → Int
        +getSvLoadLogRecord() → SvLoadLogRecord?
        +getSvDebitLogLastRecord() → SvDebitLogRecord?
        +getSvDebitLogAllRecords() → List<SvDebitLogRecord>
    }
    class "DirectoryHeader" as DirectoryHeader <<data>> <<green>> {
        +val lid: Short
        +val dfStatus: Byte

        +val accessConditions: ByteArray
        +val keyIndexes: ByteArray

        +val kif: Map<WriteAccessLevel, Byte>
        +val kvc: Map<WriteAccessLevel, Byte>
    }
    class "ElementaryFile" as ElementaryFile <<data>> <<green>> {
        +val sfi: Byte
        +val header: FileHeader?
        +<color:blue>val records: SortedMap<Int, ByteArray>
    }
    class "FileHeader" as FileHeader <<data>> <<green>> {
        +val lid: Short
        +val dfStatus: Byte?
        +val efType: ElementaryFileType

        +val recordsNumber: Int
        +val recordSize: Int

        +val accessConditions: ByteArray
        +val keyIndexes: ByteArray

        +val sharedReference: Short?
    }
    enum "ElementaryFileType" as ElementaryFileType <<green>> {
        +LINEAR
        +BINARY
        +CYCLIC
        +COUNTERS
        +SIMULATED_COUNTERS
    }
    enum "CalypsoCardProductType" as CalypsoCardProductType <<green>> {
        +PRIME_REVISION_1
        +PRIME_REVISION_2
        +PRIME_REVISION_3
        +LIGHT
        +BASIC
        +UNKNOWN
    }
    class "SvLoadLogRecord" as SvLoadLogRecord <<data>> <<green>> {
        +val rawData: ByteArray

        +val loadDate: ByteArray
        +val loadTime: ByteArray

        +val amount: Int
        +val balance: Int
        +val freeData: ByteArray

        +val kvc: Byte
        +val samId: ByteArray
        +val samTNum: Int
        +val svTNum: Int
    }
    class "SvDebitLogRecord" as SvDebitLogRecord <<data>> <<green>> {
        +val rawData: ByteArray

        +val debitDate: ByteArray
        +val debitTime: ByteArray

        +val amount: Int
        +val balance: Int

        +val kvc: Byte
        +val samId: ByteArray
        +val samTNum: Int
        +val svTNum: Int
    }
}
package "transaction" as transaction {
    ' Card
    interface "«<back:yellow><color:blue>IsoCardTransactionManager</color></back>»\nTransactionManager" as TransactionManager {
        +prepareSelectFile(lid: Short) → Self
        +prepareSelectFile(selectFileControl: SelectFileControl) → Self

        +prepareGetData(tag: GetDataTag) → Self
        +preparePutData(tag: PutDataTag, data: ByteArray) → Self

        +prepareReadRecord(sfi: Byte, recordNumber: Int) → Self
        +prepareReadRecords(sfi: Byte, fromRecordNumber: Int, toRecordNumber: Int, recordSize: Int) → Self
        +prepareReadRecordsPartially(sfi: Byte, fromRecordNumber: Int, toRecordNumber: Int, offset: Int, nbBytesToRead: Int) → Self
        +prepareReadBinary(sfi: Byte, offset: Int, nbBytesToRead: Int) → Self
        +prepareReadCounter(sfi: Byte, nbCountersToRead: Int) → Self

        +<color:blue>prepareSearchRecords(data: SearchCommandData, idCommand: Int) → Self

        +prepareCheckPinStatus() → Self

        +prepareAppendRecord(sfi: Byte, recordData: ByteArray) → Self
        +prepareUpdateRecord(sfi: Byte, recordNumber: Int, recordData: ByteArray) → Self
        +prepareWriteRecord(sfi: Byte, recordNumber: Int, recordData: ByteArray) → Self

        +prepareUpdateBinary(sfi: Byte, offset: Int, data: ByteArray) → Self
        +prepareWriteBinary(sfi: Byte, offset: Int, data: ByteArray) → Self

        +prepareIncreaseCounter(sfi: Byte, counterNumber: Int, incValue: Int) → Self
        +prepareIncreaseCounters(sfi: Byte, counterNumberToIncValueMap: Map<Int, Int>) → Self
        +prepareDecreaseCounter(sfi: Byte, counterNumber: Int, decValue: Int) → Self
        +prepareDecreaseCounters(sfi: Byte, counterNumberToDecValueMap: Map<Int, Int>) → Self
        +prepareSetCounter(sfi: Byte, counterNumber: Int, newValue: Int) → Self

        +prepareSvReadAllLogs() → Self

        +prepareVerifyPin(pin: ByteArray) → Self
        +prepareChangePin(newPin: ByteArray) → Self

        +prepareGenerateAsymmetricKeyPair() → Self

        +<color:blue>getSecureSessionStatus() → SecureSessionStatus
        +getTransactionAuditData() → List<ByteArray>
    }
    class "<color:blue>SecureSessionStatus" as SecureSessionStatus <<data>> <<green>> {
        +<color:blue>val isOpen: Boolean
        +<color:blue>val type: SecureSessionType
        +<color:blue>val writeAccessLevel: WriteAccessLevel?
    }
    enum "<color:blue>SecureSessionType" as SecureSessionType <<green>> {
        +<color:blue>SYMMETRIC
        +<color:blue>ASYMMETRIC
    }
    interface "FreeTransactionManager" as FreeTransactionManager <<blue>> extends TransactionManager {
    }
    interface "SecureTransactionManager" as SecureTransactionManager extends TransactionManager {
        +<E : CardTransactionCryptoExtension> getCryptoExtension(cryptoExtensionClass: Class<E>) → E

        +prepareCloseSecureSession() → Self
        +prepareCancelSecureSession() → Self
    }
    interface "SecureSymmetricCryptoTransactionManager" as SecureSymmetricCryptoTransactionManager extends SecureTransactionManager {
        +prepareOpenSecureSession(writeAccessLevel: WriteAccessLevel) → Self

        +prepareSvGet(svOperation: SvOperation, svAction: SvAction) → Self
        +prepareSvReload(amount: Int, date: ByteArray, time: ByteArray, free: ByteArray) → Self
        {method} <size:10><color:#7F8C8D>    ⚠ errors: SessionBufferOverflow</color></size>
        +prepareSvReload(amount: Int) → Self
        {method} <size:10><color:#7F8C8D>    ⚠ errors: SessionBufferOverflow</color></size>
        +prepareSvDebit(amount: Int, date: ByteArray, time: ByteArray) → Self
        {method} <size:10><color:#7F8C8D>    ⚠ errors: SessionBufferOverflow</color></size>
        +prepareSvDebit(amount: Int) → Self
        {method} <size:10><color:#7F8C8D>    ⚠ errors: SessionBufferOverflow</color></size>

        +prepareInvalidate() → Self
        {method} <size:10><color:#7F8C8D>    ⚠ errors: SessionBufferOverflow</color></size>
        +prepareRehabilitate() → Self
        {method} <size:10><color:#7F8C8D>    ⚠ errors: SessionBufferOverflow</color></size>

        +prepareChangeKey(keyIndex: Int, newKif: Byte, newKvc: Byte, issuerKif: Byte, issuerKvc: Byte) → Self
    }
    interface "SecureRegularModeTransactionManager" as SecureRegularModeTransactionManager <<blue>> extends SecureSymmetricCryptoTransactionManager {
    }
    interface "SecureExtendedModeTransactionManager" as SecureExtendedModeTransactionManager <<blue>> extends SecureSymmetricCryptoTransactionManager {
        +prepareEarlyMutualAuthentication() → Self
        +prepareActivateEncryption() → Self
        +prepareDeactivateEncryption() → Self
    }
    interface "SecurePkiModeTransactionManager" as SecurePkiModeTransactionManager <<blue>> extends SecureTransactionManager {
        +prepareOpenSecureSession() → Self
    }

    enum SvOperation <<green>> {
        +RELOAD
        +DEBIT
    }
    enum SvAction <<green>> {
        +DO
        +UNDO
    }
    interface "AsymmetricCryptoSecuritySetting" as AsymmetricCryptoSecuritySetting <<blue>> {
        +addPcaCertificate(pcaCertificate: PcaCertificate) → Self
        {method} <size:10><color:#7F8C8D>    ⚠ errors: InvalidCertificate</color></size>
        +addCaCertificate(caCertificate: CaCertificate) → Self
        {method} <size:10><color:#7F8C8D>    ⚠ errors: InvalidCertificate</color></size>

        +addCaCertificateParser(caCertificateParser: CaCertificateParser) → Self
        +addCardCertificateParser(cardCertificateParser: CardCertificateParser) → Self

		+<color:blue>assignOpenSecureSessionMaxDuration(csnMin: Long, dfName: ByteArray, maxDuration: Long) → Self
		+<color:blue>assignOpenSecureSessionMaxDuration(csnMin: Long, maxDuration: Long) → Self
    }
    interface "SymmetricCryptoSecuritySetting" as SymmetricCryptoSecuritySetting <<blue>> {
        +enableMultipleSession() → Self
        +enableRatificationMechanism() → Self
        +enablePinPlainTransmission() → Self
        +enableSvLoadAndDebitLog() → Self
        +authorizeSvNegativeBalance() → Self
        +disableReadOnSessionOpening() → Self

        +assignKif(writeAccessLevel: WriteAccessLevel, kvc: Byte, kif: Byte) → Self
        +assignDefaultKif(writeAccessLevel: WriteAccessLevel, kif: Byte) → Self
        +assignDefaultKvc(writeAccessLevel: WriteAccessLevel, kvc: Byte) → Self

        +addAuthorizedSessionKey(kif: Byte, kvc: Byte) → Self
        +addAuthorizedSvKey(kif: Byte, kvc: Byte) → Self

        +setPinVerificationCipheringKey(kif: Byte, kvc: Byte) → Self
        +setPinModificationCipheringKey(kif: Byte, kvc: Byte) → Self

		+<color:blue>assignOpenSecureSessionMaxDuration(csnMin: Long, dfName: ByteArray, maxDuration: Long) → Self
		+<color:blue>assignOpenSecureSessionMaxDuration(csnMin: Long, maxDuration: Long) → Self
		+<color:blue>assignSvOperationMaxDuration(csnMin: Long, dfName: ByteArray, maxDuration: Long) → Self
		+<color:blue>assignSvOperationMaxDuration(csnMin: Long, maxDuration: Long) → Self

        +initCryptoContextForNextTransaction() → Unit
        {method} <size:10><color:#7F8C8D>    ⚠ errors: Crypto, CryptoIO</color></size>
    }
    class "SearchCommandData" as SearchCommandData <<data>> <<green>> {
        +val sfi: Byte
        +val searchData: ByteArray
        +val startAtRecord: Int = 1
        +val offset: Int = 0
        +val repeatedOffset: Boolean = false
        +val mask: ByteArray? = null
        +val fetchFirstMatchingResult: Boolean = false
    }
    ' Errors
    exception "SessionBufferOverflow\nUnauthorizedKey\nInvalidPin\nInvalidCertificate\nInconsistentData\nInvalidCardSignature\nCardSignatureNotVerifiable\nSelectFile\nCrypto\nCryptoIO" as errors <<error>> <<green>> {
        +val message: String
        +val cause: Any?
    }
    package "spi" as spi {
        interface "AsymmetricCryptoCardTransactionManagerFactory" as AsymmetricCryptoCardTransactionManagerFactory <<red>> {
        }
        interface "CaCertificateParser" as CaCertificateParser <<red>> {
        }
        interface "CardCertificateParser" as CardCertificateParser <<red>> {
        }
        interface "PcaCertificate" as PcaCertificate <<red>> {
        }
        interface "CaCertificate" as CaCertificate <<red>> {
        }
        interface "CardCertificate" as CardCertificate <<red>> {
        }
        interface "SymmetricCryptoCardTransactionManagerFactory" as SymmetricCryptoCardTransactionManagerFactory <<red>> {
        }
        interface "CardTransactionCryptoExtension" as CardTransactionCryptoExtension <<red>> {
        }
    }
}

}

' Associations

TransactionManager .up.> SelectFileControl #C_USE : use >
TransactionManager .up.> GetDataTag #C_USE : use >
TransactionManager .up.> PutDataTag #C_USE : use >
TransactionManager .right.> SearchCommandData #C_USE : use >
TransactionManager .right.> SecureSessionStatus #C_LINK : provide >

SecureTransactionManager .....> CardTransactionCryptoExtension #C_LINK : provide >

SecureSymmetricCryptoTransactionManager .up.> WriteAccessLevel #C_USE : use >
SecureSymmetricCryptoTransactionManager .right.> SvOperation #C_USE : use >
SecureSymmetricCryptoTransactionManager .right.> SvAction #C_USE : use >

SymmetricCryptoSecuritySetting ..> WriteAccessLevel #C_USE : use >

AsymmetricCryptoSecuritySetting .up.> PcaCertificate #C_USE : use >
AsymmetricCryptoSecuritySetting .up.> CaCertificate #C_USE : use >
AsymmetricCryptoSecuritySetting .up.> CaCertificateParser #C_USE : use >
AsymmetricCryptoSecuritySetting .up.> CardCertificateParser #C_USE : use >

SecureSessionStatus ..> WriteAccessLevel #C_USE : use >
SecureSessionStatus ..> SecureSessionType #C_USE : use >

CalypsoCardSelectionExtension .up.> SelectFileControl #C_USE : use >
CalypsoCardSelectionExtension .up.> GetDataTag #C_USE : use >
CalypsoCardSelectionExtension ...> WriteAccessLevel #C_USE : use >

CalypsoCard ...> DirectoryHeader #C_LINK : provide >
CalypsoCard ..> ElementaryFile #C_LINK : provide >
CalypsoCard .right.> CalypsoCardProductType #C_LINK : provide >
CalypsoCard ..> SvLoadLogRecord #C_LINK : provide >
CalypsoCard ..> SvDebitLogRecord #C_LINK : provide >

DirectoryHeader .up.> WriteAccessLevel #C_USE : use >

ElementaryFile ..> FileHeader #C_USE : use >

FileHeader ..> ElementaryFileType #C_USE : use >

' == LAYOUT ==

'SymmetricCryptoSecuritySetting -[hidden]- AsymmetricCryptoSecuritySetting
AsymmetricCryptoSecuritySetting -[hidden]left- errors

AsymmetricCryptoCardTransactionManagerFactory -[hidden]- PcaCertificate
PcaCertificate -[hidden]right- CaCertificate
CaCertificate -[hidden]right- CardCertificate
CardCertificate -[hidden]right- CaCertificateParser
CaCertificateParser -[hidden]right- CardCertificateParser

' == STYLE ==

package calypsoCard #C_GREY1 {}
package calypsoCard.card #C_GREY2 {}
package calypsoCard.transaction #C_GREY2 {}
package calypsoCard.transaction.spi #C_GREY3 {}

@enduml