@startuml
title
    <img:assets/logos/calypso.svg{scale=0.2}>

    Terminal Calypso Card API 3.0.+ (2026-06-15)
end title

' == THEME (class) ==

'Couleurs issues de : https://htmlcolorcodes.com/fr/tableau-de-couleur/tableau-de-couleur-design-plat/
!define C_GREY1 F8F9F9
!define C_GREY2 F2F3F4
!define C_GREY3 E5E7E9
!define C_GREY4 D7DBDD
!define C_GREY5 CACFD2
!define C_GREY6 BDC3C7
!define C_LINK 3498DB
!define C_USE 27AE60
!define C_THROW 2C3E50

' -- Styles that don't work with new version of plantuml --
skinparam stereotypeABorderColor #A9DCDF
skinparam stereotypeIBorderColor #B4A7E5
skinparam stereotypeCBorderColor #ADD1B2
skinparam stereotypeEBorderColor #EB93DF
' -- END --

skinparam ClassBorderThickness 2
skinparam ArrowThickness 2

' Yellow
skinparam ClassBackgroundColor #FEFECE
skinparam ClassBorderColor #D4AC0D
' Red
skinparam ClassBackgroundColor<<red>> #FDEDEC
skinparam ClassBorderColor<<red>> #E74C3C
hide <<red>> stereotype
' Purple
skinparam ClassBackgroundColor<<purple>> #F4ECF7
skinparam ClassBorderColor<<purple>> #8E44AD
hide <<purple>> stereotype
' blue
skinparam ClassBackgroundColor<<blue>> #EBF5FB
skinparam ClassBorderColor<<blue>> #3498DB
hide <<blue>> stereotype
' Green
skinparam ClassBackgroundColor<<green>> #E9F7EF
skinparam ClassBorderColor<<green>> #27AE60
hide <<green>> stereotype
' Grey
skinparam ClassBackgroundColor<<grey>> #EAECEE
skinparam ClassBorderColor<<grey>> #2C3E50
hide <<grey>> stereotype

' == CONTENT ==

legend top
    * __External public API references__
    *** <back:yellow>**Calypsonet Terminal Reader API**</back>
    * __Text__
    *** <color:blue><b>New element added since the last version
    *** <color:red><s><b>Element marked as deprecated since the last version
    *** <s><b>Element marked as deprecated
    *** <color:grey><b>Work in progress...
    * __Object__
    *** <back:#EBF5FB><color:#3498DB><b>Factory or interface provided by the factory
    *** <back:#FEFECE><color:#D4AC0D><b>Interface that cannot be instantiated directly by the factory
    *** <back:#FDEDEC><color:#E74C3C><b>SPI (Service Provider Interface) to be provided by the end-user
    *** <back:#E9F7EF><color:#27AE60><b>Class, enum or exception
end legend

package "calypso.card" as calypsoCard {

+class "**final** CalypsoCardApiProperties" as ApiProperties <<green>> {
    +{static} **final** VERSION: string
}
+interface "CalypsoCardApiFactory" as CalypsoCardApiFactory <<blue>> {
    +createCalypsoCardSelectionExtension() -> CalypsoCardSelectionExtension

    +createSymmetricCryptoSecuritySetting(cryptoCardTransactionManagerFactory: SymmetricCryptoCardTransactionManagerFactory) -> SymmetricCryptoSecuritySetting
    +createAsymmetricCryptoSecuritySetting(cryptoCardTransactionManagerFactory: AsymmetricCryptoCardTransactionManagerFactory) -> AsymmetricCryptoSecuritySetting

    +createFreeTransactionManager(cardReader: <back:yellow>CardReader</back>, card: CalypsoCard) -> FreeTransactionManager
    +createSecureRegularModeTransactionManager(cardReader: <back:yellow>CardReader</back>, card: CalypsoCard, securitySetting: SymmetricCryptoSecuritySetting) -> SecureRegularModeTransactionManager
    +createSecureExtendedModeTransactionManager(cardReader: <back:yellow>CardReader</back>, card: CalypsoCard, securitySetting: SymmetricCryptoSecuritySetting) -> SecureExtendedModeTransactionManager
    +createSecurePkiModeTransactionManager(cardReader: <back:yellow>CardReader</back>, card: CalypsoCard, securitySetting: AsymmetricCryptoSecuritySetting) -> SecurePkiModeTransactionManager

    +createSearchCommandData() -> SearchCommandData
}
+enum WriteAccessLevel <<green>> {
    PERSONALIZATION
    LOAD
    DEBIT
}
+enum SelectFileControl <<green>> {
    FIRST_EF
    NEXT_EF
    CURRENT_DF
}
+enum GetDataTag <<green>> {
    FCP_FOR_CURRENT_FILE
    FCI_FOR_CURRENT_DF
    EF_LIST
    TRACEABILITY_INFORMATION
    CARD_PUBLIC_KEY
    CARD_CERTIFICATE
    CA_CERTIFICATE
}
+enum "PutDataTag" as PutDataTag <<green>> {
    CARD_KEY_PAIR
    CARD_CERTIFICATE
    CA_CERTIFICATE
}
package "card" as card {
    +interface "<<<back:yellow>CardSelectionExtension</back>>>\nCalypsoCardSelectionExtension" as CalypsoCardSelectionExtension <<blue>> {
        +acceptInvalidatedCard() -> CalypsoCardSelectionExtension

        +prepareSelectFile(lid: short) -> CalypsoCardSelectionExtension
        +prepareSelectFile(selectControl: SelectFileControl) -> CalypsoCardSelectionExtension

        +prepareGetData(tag: GetDataTag) -> CalypsoCardSelectionExtension

        +prepareReadRecord(sfi: byte, recordNumber: integer) -> CalypsoCardSelectionExtension
        +prepareReadBinary(sfi: byte, offset: integer, nbBytesToRead: integer) -> CalypsoCardSelectionExtension
        +prepareReadCounter(sfi: byte, nbCountersToRead: integer) -> CalypsoCardSelectionExtension

        +preparePreOpenSecureSession(writeAccessLevel: WriteAccessLevel) -> CalypsoCardSelectionExtension
    }
    +interface "<<<back:yellow>IsoSmartCard</back>>>\nCalypsoCard" as CalypsoCard {
        +getProductType() -> ProductType
        +isHce() -> boolean

        +isDfInvalidated() -> boolean

        +getDfName() -> byte array
        +getApplicationSerialNumber() -> byte array

        +getStartupInfoRawData() -> byte array
        +getPlatform() -> byte
        +getApplicationType() -> byte
        +getApplicationSubtype() -> byte
        +getSoftwareIssuer() -> byte
        +getSoftwareVersion() -> byte
        +getSoftwareRevision() -> byte
        +getSessionModification() -> byte

        +getTraceabilityInformation() -> byte array

        +getCardPublicKey() -> byte array
        +getCardCertificate() -> byte array
        +getCaCertificate() -> byte array

        +getDirectoryHeader() -> DirectoryHeader?
        +getFileBySfi(sfi: byte) -> ElementaryFile?
        +getFileByLid(lid: short) -> ElementaryFile?
        +getFiles() -> set<ElementaryFile>

        +isDfRatified() -> boolean
        +getTransactionCounter() -> integer

        +isPkiModeSupported() -> boolean
        +isExtendedModeSupported() -> boolean
        +isRatificationOnDeselectSupported() -> boolean

        +isPinFeatureAvailable() -> boolean
        +isPinBlocked() -> boolean
        +getPinAttemptRemaining() -> integer

        +isSvFeatureAvailable() -> boolean
        +getSvBalance() -> integer
        +getSvLastTNum() -> integer
        +getSvLoadLogRecord() -> SvLoadLogRecord?
        +getSvDebitLogLastRecord() -> SvDebitLogRecord?
        +getSvDebitLogAllRecords() -> list<SvDebitLogRecord>
    }
    +interface DirectoryHeader {
        +getLid() -> short
        +getDfStatus() -> byte

        +getAccessConditions() -> byte array
        +getKeyIndexes() -> byte array

        +getKif(writeAccessLevel: WriteAccessLevel) -> byte
        +getKvc(writeAccessLevel: WriteAccessLevel) -> byte
    }
    +interface ElementaryFile {
        +getSfi() -> byte
        +getHeader() -> FileHeader?
        +getData() -> FileData
    }
    +interface FileHeader {
        +getLid() -> short
        +getDfStatus() -> byte?
        +getEfType() -> ElementaryFile.Type

        +getRecordsNumber() -> integer
        +getRecordSize() -> integer

        +getAccessConditions() -> byte array
        +getKeyIndexes() -> byte array

        +getSharedReference() -> short?
    }
    +enum "Type" as FileType <<green>> {
        LINEAR
        BINARY
        CYCLIC
        COUNTERS
        SIMULATED_COUNTERS
    }
    +interface FileData {
        +getContent() -> byte array
        +getContent(numRecord: integer) -> byte array
        +getContent(numRecord: integer, dataOffset: integer, dataLength: integer) -> byte array
        +getAllRecordsContent() -> sortedMap<integer, byte array>

        +getContentAsCounterValue(numCounter: integer) -> integer?
        +getAllCountersValue() -> sortedMap<integer, integer>
    }
    +enum "ProductType" as CardProductType <<green>> {
        PRIME_REVISION_1
        PRIME_REVISION_2
        PRIME_REVISION_3
        LIGHT
        BASIC
        UNKNOWN
    }
    +interface SvLoadLogRecord {
        +getRawData() -> byte array

        +getLoadDate() -> byte array
        +getLoadTime() -> byte array

        +getAmount() -> integer
        +getBalance() -> integer
        +getFreeData() -> byte array

        +getKvc() -> byte
        +getSamId() -> byte array
        +getSamTNum() -> integer
        +getSvTNum() -> integer
    }
    +interface SvDebitLogRecord {
        +getRawData() -> byte array

        +getDebitDate() -> byte array
        +getDebitTime() -> byte array

        +getAmount() -> integer
        +getBalance() -> integer

        +getKvc() -> byte
        +getSamId() -> byte array
        +getSamTNum() -> integer
        +getSvTNum() -> integer
    }
}
package "transaction" as transaction {
    ' Card
    +interface "<<<back:yellow><color:blue>IsoCardTransactionManager</color></back>>>\nTransactionManager" as TransactionManager<T : TransactionManager<T>> {
        +prepareSelectFile(lid: short) -> T
        +prepareSelectFile(selectFileControl: SelectFileControl) -> T

        +prepareGetData(tag: GetDataTag) -> T
        +preparePutData(tag: PutDataTag, data: byte array) -> T

        +prepareReadRecord(sfi: byte, recordNumber: integer) -> T
        +prepareReadRecords(sfi: byte, fromRecordNumber: integer, toRecordNumber: integer, recordSize: integer) -> T
        +prepareReadRecordsPartially(sfi: byte, fromRecordNumber: integer, toRecordNumber: integer, offset: integer, nbBytesToRead: integer) -> T
        +prepareReadBinary(sfi: byte, offset: integer, nbBytesToRead: integer) -> T
        +prepareReadCounter(sfi: byte, nbCountersToRead: integer) -> T

        +prepareSearchRecords(data: SearchCommandData) -> T

        +prepareCheckPinStatus() -> T

        +prepareAppendRecord(sfi: byte, recordData: byte array) -> T
        +prepareUpdateRecord(sfi: byte, recordNumber: integer, recordData: byte array) -> T
        +prepareWriteRecord(sfi: byte, recordNumber: integer, recordData: byte array) -> T

        +prepareUpdateBinary(sfi: byte, offset: integer, data: byte array) -> T
        +prepareWriteBinary(sfi: byte, offset: integer, data: byte array) -> T

        +prepareIncreaseCounter(sfi: byte, counterNumber: integer, incValue: integer) -> T
        +prepareIncreaseCounters(sfi: byte, counterNumberToIncValueMap: map<integer, integer>) -> T
        +prepareDecreaseCounter(sfi: byte, counterNumber: integer, decValue: integer) -> T
        +prepareDecreaseCounters(sfi: byte, counterNumberToDecValueMap: map<integer, integer>) -> T
        +prepareSetCounter(sfi: byte, counterNumber: integer, newValue: integer) -> T

        +prepareSvReadAllLogs() -> T

        +prepareVerifyPin(pin: byte array) -> T
        +prepareChangePin(newPin: byte array) -> T

        +prepareGenerateAsymmetricKeyPair() -> T

        +<color:blue>getSecureSessionStatus() -> SecureSessionStatus
        +getTransactionAuditData() -> list<byte array>
    }
    +interface "<color:blue>SecureSessionStatus" as SecureSessionStatus {
        +<color:blue>isOpen() -> boolean
        +<color:blue>getType() -> SecureSessionType
        +<color:blue>getWriteAccessLevel() -> WriteAccessLevel?
    }
    +enum "<color:blue>SecureSessionType" as SecureSessionType <<green>> {
        <color:blue>SYMMETRIC
        <color:blue>ASYMMETRIC
    }
    +interface "FreeTransactionManager" as FreeTransactionManager <<blue>> extends TransactionManager {
    }
    +interface "SecureTransactionManager" as SecureTransactionManager<T : SecureTransactionManager<T>> extends TransactionManager {
        +<E : CardTransactionCryptoExtension> getCryptoExtension(cryptoExtensionClass: Class<E>) -> E

        +prepareCloseSecureSession() -> T
        +prepareCancelSecureSession() -> T
    }
    +interface "SecureSymmetricCryptoTransactionManager" as SecureSymmetricCryptoTransactionManager<T : SecureSymmetricCryptoTransactionManager<T>> extends SecureTransactionManager {
        +prepareOpenSecureSession(writeAccessLevel: WriteAccessLevel) -> T

        +prepareSvGet(svOperation: SvOperation, svAction: SvAction) -> T
        +prepareSvReload(amount: integer, date: byte array, time: byte array, free: byte array) -> T
        +prepareSvReload(amount: integer) -> T
        +prepareSvDebit(amount: integer, date: byte array, time: byte array) -> T
        +prepareSvDebit(amount: integer) -> T

        +prepareInvalidate() -> T
        +prepareRehabilitate() -> T

        +prepareChangeKey(keyIndex: integer, newKif: byte, newKvc: byte, issuerKif: byte, issuerKvc: byte) -> T
    }
    +interface "SecureRegularModeTransactionManager" as SecureRegularModeTransactionManager <<blue>> extends SecureSymmetricCryptoTransactionManager {
    }
    +interface "SecureExtendedModeTransactionManager" as SecureExtendedModeTransactionManager <<blue>> extends SecureSymmetricCryptoTransactionManager {
        +prepareEarlyMutualAuthentication() -> SecureExtendedModeTransactionManager
        +prepareActivateEncryption() -> SecureExtendedModeTransactionManager
        +prepareDeactivateEncryption() -> SecureExtendedModeTransactionManager
    }
    +interface "SecurePkiModeTransactionManager" as SecurePkiModeTransactionManager <<blue>> extends SecureTransactionManager {
        +prepareOpenSecureSession() -> SecurePkiModeTransactionManager
    }

    +enum SvOperation <<green>> {
        RELOAD
        DEBIT
    }
    +enum SvAction <<green>> {
        DO
        UNDO
    }
    +interface "AsymmetricCryptoSecuritySetting" as AsymmetricCryptoSecuritySetting <<blue>> {
        +addPcaCertificate(pcaCertificate: PcaCertificate) -> AsymmetricCryptoSecuritySetting
        +addCaCertificate(caCertificate: CaCertificate) -> AsymmetricCryptoSecuritySetting

        +addCaCertificateParser(caCertificateParser: CaCertificateParser) -> AsymmetricCryptoSecuritySetting
        +addCardCertificateParser(cardCertificateParser: CardCertificateParser) -> AsymmetricCryptoSecuritySetting

		+<color:blue>assignOpenSecureSessionMaxDuration(csnMin: long, dfName: byte array, maxDuration: long) -> AsymmetricCryptoSecuritySetting
		+<color:blue>assignOpenSecureSessionMaxDuration(csnMin: long, maxDuration: long) -> AsymmetricCryptoSecuritySetting
    }
    +interface "SymmetricCryptoSecuritySetting" as SymmetricCryptoSecuritySetting <<blue>> {
        +enableMultipleSession() -> SymmetricCryptoSecuritySetting
        +enableRatificationMechanism() -> SymmetricCryptoSecuritySetting
        +enablePinPlainTransmission() -> SymmetricCryptoSecuritySetting
        +enableSvLoadAndDebitLog() -> SymmetricCryptoSecuritySetting
        +authorizeSvNegativeBalance() -> SymmetricCryptoSecuritySetting
        +disableReadOnSessionOpening() -> SymmetricCryptoSecuritySetting

        +assignKif(writeAccessLevel: WriteAccessLevel, kvc: byte, kif: byte) -> SymmetricCryptoSecuritySetting
        +assignDefaultKif(writeAccessLevel: WriteAccessLevel, kif: byte) -> SymmetricCryptoSecuritySetting
        +assignDefaultKvc(writeAccessLevel: WriteAccessLevel, kvc: byte) -> SymmetricCryptoSecuritySetting

        +addAuthorizedSessionKey(kif: byte, kvc: byte) -> SymmetricCryptoSecuritySetting
        +addAuthorizedSvKey(kif: byte, kvc: byte) -> SymmetricCryptoSecuritySetting

        +setPinVerificationCipheringKey(kif: byte, kvc: byte) -> SymmetricCryptoSecuritySetting
        +setPinModificationCipheringKey(kif: byte, kvc: byte) -> SymmetricCryptoSecuritySetting

		+<color:blue>assignOpenSecureSessionMaxDuration(csnMin: long, dfName: byte array, maxDuration: long) -> SymmetricCryptoSecuritySetting
		+<color:blue>assignOpenSecureSessionMaxDuration(csnMin: long, maxDuration: long) -> SymmetricCryptoSecuritySetting
		+<color:blue>assignSvOperationMaxDuration(csnMin: long, dfName: byte array, maxDuration: long) -> SymmetricCryptoSecuritySetting
		+<color:blue>assignSvOperationMaxDuration(csnMin: long, maxDuration: long) -> SymmetricCryptoSecuritySetting

        +initCryptoContextForNextTransaction() -> unit
    }
    +interface SearchCommandData <<blue>> {
        +setSfi(sfi: byte) -> SearchCommandData
        +startAtRecord(recordNumber: integer) -> SearchCommandData
        +setOffset(offset: integer) -> SearchCommandData
        +enableRepeatedOffset() -> SearchCommandData
        +setSearchData(data: byte array) -> SearchCommandData
        +setMask(mask: byte array) -> SearchCommandData
        +fetchFirstMatchingResult() -> SearchCommandData

        +getMatchingRecordNumbers() -> list<integer>
    }
    ' Exceptions
    +class "<<RuntimeException>>" as RuntimeException <<green>> {
        +**SessionBufferOverflowException**: Session buffer would overflow for atomic session.
        +**UnauthorizedKeyException**
        +**InvalidPinException**
        +**InvalidCertificateException**
        +**InconsistentDataException**: Number of R-APDUs != number of C-APDUs **or** data read in session != data read outside session.
        +**InvalidCardSignatureException**
        +**CardSignatureNotVerifiableException**: CloseSecureSession is successful but crypto resource is no more available to check the card MAC.
        +**SelectFileException**
        +<s>**UnexpectedCommandStatusException**
        +<s>**ReaderIOException**: Card reader communication is broken.
        +<s>**CardIOException**
        +**CryptoException**
        +**CryptoIOException**: Crypto reader or Crypto card communication is broken.
    }
    package "spi" as spi {
        +interface "AsymmetricCryptoCardTransactionManagerFactory" as AsymmetricCryptoCardTransactionManagerFactory <<red>> {
        }
        +interface "CaCertificateParser" as CaCertificateParser <<red>> {
        }
        +interface "CardCertificateParser" as CardCertificateParser <<red>> {
        }
        +interface "PcaCertificate" as PcaCertificate <<red>> {
        }
        +interface "CaCertificate" as CaCertificate <<red>> {
        }
        +interface "CardCertificate" as CardCertificate <<red>> {
        }
        +interface "SymmetricCryptoCardTransactionManagerFactory" as SymmetricCryptoCardTransactionManagerFactory <<red>> {
        }
        +interface "CardTransactionCryptoExtension" as CardTransactionCryptoExtension <<red>> {
        }
    }
}

}

' Associations

TransactionManager .up.> SelectFileControl #C_USE : use >
TransactionManager .up.> GetDataTag #C_USE : use >
TransactionManager .up.> PutDataTag #C_USE : use >
TransactionManager .right.> SearchCommandData #C_USE : use >
TransactionManager .right.> SecureSessionStatus #C_LINK : provide >

SecureTransactionManager .....> CardTransactionCryptoExtension #C_LINK : provide >

SecureSymmetricCryptoTransactionManager .up.> WriteAccessLevel #C_USE : use >
SecureSymmetricCryptoTransactionManager .right.> SvOperation #C_USE : use >
SecureSymmetricCryptoTransactionManager .right.> SvAction #C_USE : use >

SymmetricCryptoSecuritySetting ..> WriteAccessLevel #C_USE : use >

AsymmetricCryptoSecuritySetting .up.> PcaCertificate #C_USE : use >
AsymmetricCryptoSecuritySetting .up.> CaCertificate #C_USE : use >
AsymmetricCryptoSecuritySetting .up.> CaCertificateParser #C_USE : use >
AsymmetricCryptoSecuritySetting .up.> CardCertificateParser #C_USE : use >

SecureSessionStatus ..> WriteAccessLevel #C_LINK : provide >
SecureSessionStatus ..> SecureSessionType #C_LINK : provide >

CalypsoCardSelectionExtension .up.> SelectFileControl #C_USE : use >
CalypsoCardSelectionExtension .up.> GetDataTag #C_USE : use >
CalypsoCardSelectionExtension .up.> WriteAccessLevel #C_USE : use >

CalypsoCard ..> DirectoryHeader #C_LINK : provide >
CalypsoCard ..> ElementaryFile #C_LINK : provide >
CalypsoCard +-right- CardProductType
CalypsoCard .right.> CardProductType #C_LINK : provide >
CalypsoCard ..> SvLoadLogRecord #C_LINK : provide >
CalypsoCard ..> SvDebitLogRecord #C_LINK : provide >

DirectoryHeader ..> WriteAccessLevel #C_USE : use >

ElementaryFile +-- FileType
ElementaryFile ...> FileHeader #C_LINK : provide >
ElementaryFile ...> FileData #C_LINK : provide >

FileHeader .up.> FileType #C_LINK : provide >

' == LAYOUT ==

'SymmetricCryptoSecuritySetting -[hidden]- AsymmetricCryptoSecuritySetting
AsymmetricCryptoSecuritySetting -[hidden]left- RuntimeException

AsymmetricCryptoCardTransactionManagerFactory -[hidden]- PcaCertificate
PcaCertificate -[hidden]right- CaCertificate
CaCertificate -[hidden]right- CardCertificate
CardCertificate -[hidden]right- CaCertificateParser
CaCertificateParser -[hidden]right- CardCertificateParser

' == STYLE ==

package calypsoCard #C_GREY1 {}
package calypsoCard.card #C_GREY2 {}
package calypsoCard.transaction #C_GREY2 {}
package calypsoCard.transaction.spi #C_GREY3 {}

@enduml