@startuml
title
    <img:assets/logos/calypso.svg{scale=0.2}>

    Terminal Calypso Card API 3.0.+ (2026-06-15)
end title

' == THEME (class) ==

'Couleurs issues de : https://htmlcolorcodes.com/fr/tableau-de-couleur/tableau-de-couleur-design-plat/
!define C_GREY1 F8F9F9
!define C_GREY2 F2F3F4
!define C_GREY3 E5E7E9
!define C_GREY4 D7DBDD
!define C_GREY5 CACFD2
!define C_GREY6 BDC3C7
!define C_LINK 3498DB
!define C_USE 27AE60
!define C_THROW 2C3E50

' -- Styles that don't work with new version of plantuml --
skinparam stereotypeABorderColor #A9DCDF
skinparam stereotypeIBorderColor #B4A7E5
skinparam stereotypeCBorderColor #ADD1B2
skinparam stereotypeEBorderColor #EB93DF
' -- END --

skinparam ClassBorderThickness 2
skinparam ArrowThickness 2

' Yellow
skinparam ClassBackgroundColor #FEFECE
skinparam ClassBorderColor #D4AC0D
' Red
skinparam ClassBackgroundColor<<red>> #FDEDEC
skinparam ClassBorderColor<<red>> #E74C3C
hide <<red>> stereotype
' Purple
skinparam ClassBackgroundColor<<purple>> #F4ECF7
skinparam ClassBorderColor<<purple>> #8E44AD
hide <<purple>> stereotype
' blue
skinparam ClassBackgroundColor<<blue>> #EBF5FB
skinparam ClassBorderColor<<blue>> #3498DB
hide <<blue>> stereotype
' Green
skinparam ClassBackgroundColor<<green>> #E9F7EF
skinparam ClassBorderColor<<green>> #27AE60
hide <<green>> stereotype
' Grey
skinparam ClassBackgroundColor<<grey>> #EAECEE
skinparam ClassBorderColor<<grey>> #2C3E50
hide <<grey>> stereotype

' == CONTENT ==

legend top
    * __External public API references__
    *** <back:yellow>**Calypsonet Terminal Reader API**</back>
    * __Text__
    *** <color:blue><b>New element added since the last version
    *** <color:red><s><b>Element marked as deprecated since the last version
    *** <s><b>Element marked as deprecated
    *** <color:grey><b>Work in progress...
    * __Object__
    *** <back:#EBF5FB><color:#3498DB><b>Factory or interface provided by the factory
    *** <back:#FEFECE><color:#D4AC0D><b>Interface that cannot be instantiated directly by the factory
    *** <back:#FDEDEC><color:#E74C3C><b>SPI (Service Provider Interface) to be provided by the end-user
    *** <back:#E9F7EF><color:#27AE60><b>Class, enum or error
end legend

package "calypso.card" as calypsoCard {

+class "**final** CalypsoCardApiProperties" as ApiProperties <<green>> {
    +{static} **final** VERSION: String
}
+interface "CalypsoCardApiFactory" as CalypsoCardApiFactory <<blue>> {
    +createCalypsoCardSelectionExtension() → CalypsoCardSelectionExtension

    +createSymmetricCryptoSecuritySetting(cryptoCardTransactionManagerFactory: SymmetricCryptoCardTransactionManagerFactory) → SymmetricCryptoSecuritySetting
    +createAsymmetricCryptoSecuritySetting(cryptoCardTransactionManagerFactory: AsymmetricCryptoCardTransactionManagerFactory) → AsymmetricCryptoSecuritySetting

    +createFreeTransactionManager(cardReader: <back:yellow>CardReader</back>, card: CalypsoCard) → FreeTransactionManager
    +createSecureRegularModeTransactionManager(cardReader: <back:yellow>CardReader</back>, card: CalypsoCard, securitySetting: SymmetricCryptoSecuritySetting) → SecureRegularModeTransactionManager
    +createSecureExtendedModeTransactionManager(cardReader: <back:yellow>CardReader</back>, card: CalypsoCard, securitySetting: SymmetricCryptoSecuritySetting) → SecureExtendedModeTransactionManager
    +createSecurePkiModeTransactionManager(cardReader: <back:yellow>CardReader</back>, card: CalypsoCard, securitySetting: AsymmetricCryptoSecuritySetting) → SecurePkiModeTransactionManager

    +createSearchCommandData() → SearchCommandData
}
+enum WriteAccessLevel <<green>> {
    PERSONALIZATION
    LOAD
    DEBIT
}
+enum SelectFileControl <<green>> {
    FIRST_EF
    NEXT_EF
    CURRENT_DF
}
+enum GetDataTag <<green>> {
    FCP_FOR_CURRENT_FILE
    FCI_FOR_CURRENT_DF
    EF_LIST
    TRACEABILITY_INFORMATION
    CARD_PUBLIC_KEY
    CARD_CERTIFICATE
    CA_CERTIFICATE
}
+enum "PutDataTag" as PutDataTag <<green>> {
    CARD_KEY_PAIR
    CARD_CERTIFICATE
    CA_CERTIFICATE
}
package "card" as card {
    +interface "<<<back:yellow>CardSelectionExtension</back>>>\nCalypsoCardSelectionExtension" as CalypsoCardSelectionExtension <<blue>> {
        +acceptInvalidatedCard() → CalypsoCardSelectionExtension

        +prepareSelectFile(lid: Short) → CalypsoCardSelectionExtension
        +prepareSelectFile(selectControl: SelectFileControl) → CalypsoCardSelectionExtension

        +prepareGetData(tag: GetDataTag) → CalypsoCardSelectionExtension

        +prepareReadRecord(sfi: Byte, recordNumber: Int) → CalypsoCardSelectionExtension
        +prepareReadBinary(sfi: Byte, offset: Int, nbBytesToRead: Int) → CalypsoCardSelectionExtension
        +prepareReadCounter(sfi: Byte, nbCountersToRead: Int) → CalypsoCardSelectionExtension

        +preparePreOpenSecureSession(writeAccessLevel: WriteAccessLevel) → CalypsoCardSelectionExtension
    }
    +interface "<<<back:yellow>IsoSmartCard</back>>>\nCalypsoCard" as CalypsoCard {
        +getProductType() → ProductType
        +isHce() → Boolean

        +isDfInvalidated() → Boolean

        +getDfName() → ByteArray
        +getApplicationSerialNumber() → ByteArray

        +getStartupInfoRawData() → ByteArray
        +getPlatform() → Byte
        +getApplicationType() → Byte
        +getApplicationSubtype() → Byte
        +getSoftwareIssuer() → Byte
        +getSoftwareVersion() → Byte
        +getSoftwareRevision() → Byte
        +getSessionModification() → Byte

        +getTraceabilityInformation() → ByteArray

        +getCardPublicKey() → ByteArray
        +getCardCertificate() → ByteArray
        +getCaCertificate() → ByteArray

        +getDirectoryHeader() → DirectoryHeader?
        +getFileBySfi(sfi: Byte) → ElementaryFile?
        +getFileByLid(lid: Short) → ElementaryFile?
        +getFiles() → Set<ElementaryFile>

        +isDfRatified() → Boolean
        +getTransactionCounter() → Int

        +isPkiModeSupported() → Boolean
        +isExtendedModeSupported() → Boolean
        +isRatificationOnDeselectSupported() → Boolean

        +isPinFeatureAvailable() → Boolean
        +isPinBlocked() → Boolean
        +getPinAttemptRemaining() → Int

        +isSvFeatureAvailable() → Boolean
        +getSvBalance() → Int
        +getSvLastTNum() → Int
        +getSvLoadLogRecord() → SvLoadLogRecord?
        +getSvDebitLogLastRecord() → SvDebitLogRecord?
        +getSvDebitLogAllRecords() → List<SvDebitLogRecord>
    }
    +interface DirectoryHeader {
        +getLid() → Short
        +getDfStatus() → Byte

        +getAccessConditions() → ByteArray
        +getKeyIndexes() → ByteArray

        +getKif(writeAccessLevel: WriteAccessLevel) → Byte
        +getKvc(writeAccessLevel: WriteAccessLevel) → Byte
    }
    +interface ElementaryFile {
        +getSfi() → Byte
        +getHeader() → FileHeader?
        +getData() → FileData
    }
    +interface FileHeader {
        +getLid() → Short
        +getDfStatus() → Byte?
        +getEfType() → ElementaryFile.Type

        +getRecordsNumber() → Int
        +getRecordSize() → Int

        +getAccessConditions() → ByteArray
        +getKeyIndexes() → ByteArray

        +getSharedReference() → Short?
    }
    +enum "Type" as FileType <<green>> {
        LINEAR
        BINARY
        CYCLIC
        COUNTERS
        SIMULATED_COUNTERS
    }
    +interface FileData {
        +getContent() → ByteArray
        +getContent(numRecord: Int) → ByteArray
        +getContent(numRecord: Int, dataOffset: Int, dataLength: Int) → ByteArray
        +getAllRecordsContent() → SortedMap<Int, ByteArray>

        +getContentAsCounterValue(numCounter: Int) → Int?
        +getAllCountersValue() → SortedMap<Int, Int>
    }
    +enum "ProductType" as CardProductType <<green>> {
        PRIME_REVISION_1
        PRIME_REVISION_2
        PRIME_REVISION_3
        LIGHT
        BASIC
        UNKNOWN
    }
    +interface SvLoadLogRecord {
        +getRawData() → ByteArray

        +getLoadDate() → ByteArray
        +getLoadTime() → ByteArray

        +getAmount() → Int
        +getBalance() → Int
        +getFreeData() → ByteArray

        +getKvc() → Byte
        +getSamId() → ByteArray
        +getSamTNum() → Int
        +getSvTNum() → Int
    }
    +interface SvDebitLogRecord {
        +getRawData() → ByteArray

        +getDebitDate() → ByteArray
        +getDebitTime() → ByteArray

        +getAmount() → Int
        +getBalance() → Int

        +getKvc() → Byte
        +getSamId() → ByteArray
        +getSamTNum() → Int
        +getSvTNum() → Int
    }
}
package "transaction" as transaction {
    ' Card
    +interface "<<<back:yellow><color:blue>IsoCardTransactionManager</color></back>>>\nTransactionManager" as TransactionManager<T : TransactionManager<T>> {
        +prepareSelectFile(lid: Short) → T
        +prepareSelectFile(selectFileControl: SelectFileControl) → T

        +prepareGetData(tag: GetDataTag) → T
        +preparePutData(tag: PutDataTag, data: ByteArray) → T

        +prepareReadRecord(sfi: Byte, recordNumber: Int) → T
        +prepareReadRecords(sfi: Byte, fromRecordNumber: Int, toRecordNumber: Int, recordSize: Int) → T
        +prepareReadRecordsPartially(sfi: Byte, fromRecordNumber: Int, toRecordNumber: Int, offset: Int, nbBytesToRead: Int) → T
        +prepareReadBinary(sfi: Byte, offset: Int, nbBytesToRead: Int) → T
        +prepareReadCounter(sfi: Byte, nbCountersToRead: Int) → T

        +prepareSearchRecords(data: SearchCommandData) → T

        +prepareCheckPinStatus() → T

        +prepareAppendRecord(sfi: Byte, recordData: ByteArray) → T
        +prepareUpdateRecord(sfi: Byte, recordNumber: Int, recordData: ByteArray) → T
        +prepareWriteRecord(sfi: Byte, recordNumber: Int, recordData: ByteArray) → T

        +prepareUpdateBinary(sfi: Byte, offset: Int, data: ByteArray) → T
        +prepareWriteBinary(sfi: Byte, offset: Int, data: ByteArray) → T

        +prepareIncreaseCounter(sfi: Byte, counterNumber: Int, incValue: Int) → T
        +prepareIncreaseCounters(sfi: Byte, counterNumberToIncValueMap: Map<Int, Int>) → T
        +prepareDecreaseCounter(sfi: Byte, counterNumber: Int, decValue: Int) → T
        +prepareDecreaseCounters(sfi: Byte, counterNumberToDecValueMap: Map<Int, Int>) → T
        +prepareSetCounter(sfi: Byte, counterNumber: Int, newValue: Int) → T

        +prepareSvReadAllLogs() → T

        +prepareVerifyPin(pin: ByteArray) → T
        +prepareChangePin(newPin: ByteArray) → T

        +prepareGenerateAsymmetricKeyPair() → T

        +<color:blue>getSecureSessionStatus() → SecureSessionStatus
        +getTransactionAuditData() → List<ByteArray>
    }
    +interface "<color:blue>SecureSessionStatus" as SecureSessionStatus {
        +<color:blue>isOpen() → Boolean
        +<color:blue>getType() → SecureSessionType
        +<color:blue>getWriteAccessLevel() → WriteAccessLevel?
    }
    +enum "<color:blue>SecureSessionType" as SecureSessionType <<green>> {
        <color:blue>SYMMETRIC
        <color:blue>ASYMMETRIC
    }
    +interface "FreeTransactionManager" as FreeTransactionManager <<blue>> extends TransactionManager {
    }
    +interface "SecureTransactionManager" as SecureTransactionManager<T : SecureTransactionManager<T>> extends TransactionManager {
        +<E : CardTransactionCryptoExtension> getCryptoExtension(cryptoExtensionClass: Class<E>) → E

        +prepareCloseSecureSession() → T
        +prepareCancelSecureSession() → T
    }
    +interface "SecureSymmetricCryptoTransactionManager" as SecureSymmetricCryptoTransactionManager<T : SecureSymmetricCryptoTransactionManager<T>> extends SecureTransactionManager {
        +prepareOpenSecureSession(writeAccessLevel: WriteAccessLevel) → T

        +prepareSvGet(svOperation: SvOperation, svAction: SvAction) → T
        +prepareSvReload(amount: Int, date: ByteArray, time: ByteArray, free: ByteArray) → T
        +prepareSvReload(amount: Int) → T
        +prepareSvDebit(amount: Int, date: ByteArray, time: ByteArray) → T
        +prepareSvDebit(amount: Int) → T

        +prepareInvalidate() → T
        +prepareRehabilitate() → T

        +prepareChangeKey(keyIndex: Int, newKif: Byte, newKvc: Byte, issuerKif: Byte, issuerKvc: Byte) → T
    }
    +interface "SecureRegularModeTransactionManager" as SecureRegularModeTransactionManager <<blue>> extends SecureSymmetricCryptoTransactionManager {
    }
    +interface "SecureExtendedModeTransactionManager" as SecureExtendedModeTransactionManager <<blue>> extends SecureSymmetricCryptoTransactionManager {
        +prepareEarlyMutualAuthentication() → SecureExtendedModeTransactionManager
        +prepareActivateEncryption() → SecureExtendedModeTransactionManager
        +prepareDeactivateEncryption() → SecureExtendedModeTransactionManager
    }
    +interface "SecurePkiModeTransactionManager" as SecurePkiModeTransactionManager <<blue>> extends SecureTransactionManager {
        +prepareOpenSecureSession() → SecurePkiModeTransactionManager
    }

    +enum SvOperation <<green>> {
        RELOAD
        DEBIT
    }
    +enum SvAction <<green>> {
        DO
        UNDO
    }
    +interface "AsymmetricCryptoSecuritySetting" as AsymmetricCryptoSecuritySetting <<blue>> {
        +addPcaCertificate(pcaCertificate: PcaCertificate) → AsymmetricCryptoSecuritySetting
        +addCaCertificate(caCertificate: CaCertificate) → AsymmetricCryptoSecuritySetting

        +addCaCertificateParser(caCertificateParser: CaCertificateParser) → AsymmetricCryptoSecuritySetting
        +addCardCertificateParser(cardCertificateParser: CardCertificateParser) → AsymmetricCryptoSecuritySetting

		+<color:blue>assignOpenSecureSessionMaxDuration(csnMin: Long, dfName: ByteArray, maxDuration: Long) → AsymmetricCryptoSecuritySetting
		+<color:blue>assignOpenSecureSessionMaxDuration(csnMin: Long, maxDuration: Long) → AsymmetricCryptoSecuritySetting
    }
    +interface "SymmetricCryptoSecuritySetting" as SymmetricCryptoSecuritySetting <<blue>> {
        +enableMultipleSession() → SymmetricCryptoSecuritySetting
        +enableRatificationMechanism() → SymmetricCryptoSecuritySetting
        +enablePinPlainTransmission() → SymmetricCryptoSecuritySetting
        +enableSvLoadAndDebitLog() → SymmetricCryptoSecuritySetting
        +authorizeSvNegativeBalance() → SymmetricCryptoSecuritySetting
        +disableReadOnSessionOpening() → SymmetricCryptoSecuritySetting

        +assignKif(writeAccessLevel: WriteAccessLevel, kvc: Byte, kif: Byte) → SymmetricCryptoSecuritySetting
        +assignDefaultKif(writeAccessLevel: WriteAccessLevel, kif: Byte) → SymmetricCryptoSecuritySetting
        +assignDefaultKvc(writeAccessLevel: WriteAccessLevel, kvc: Byte) → SymmetricCryptoSecuritySetting

        +addAuthorizedSessionKey(kif: Byte, kvc: Byte) → SymmetricCryptoSecuritySetting
        +addAuthorizedSvKey(kif: Byte, kvc: Byte) → SymmetricCryptoSecuritySetting

        +setPinVerificationCipheringKey(kif: Byte, kvc: Byte) → SymmetricCryptoSecuritySetting
        +setPinModificationCipheringKey(kif: Byte, kvc: Byte) → SymmetricCryptoSecuritySetting

		+<color:blue>assignOpenSecureSessionMaxDuration(csnMin: Long, dfName: ByteArray, maxDuration: Long) → SymmetricCryptoSecuritySetting
		+<color:blue>assignOpenSecureSessionMaxDuration(csnMin: Long, maxDuration: Long) → SymmetricCryptoSecuritySetting
		+<color:blue>assignSvOperationMaxDuration(csnMin: Long, dfName: ByteArray, maxDuration: Long) → SymmetricCryptoSecuritySetting
		+<color:blue>assignSvOperationMaxDuration(csnMin: Long, maxDuration: Long) → SymmetricCryptoSecuritySetting

        +initCryptoContextForNextTransaction() → Unit
    }
    +interface SearchCommandData <<blue>> {
        +setSfi(sfi: Byte) → SearchCommandData
        +startAtRecord(recordNumber: Int) → SearchCommandData
        +setOffset(offset: Int) → SearchCommandData
        +enableRepeatedOffset() → SearchCommandData
        +setSearchData(data: ByteArray) → SearchCommandData
        +setMask(mask: ByteArray) → SearchCommandData
        +fetchFirstMatchingResult() → SearchCommandData

        +getMatchingRecordNumbers() → List<Int>
    }
    ' Errors
    +exception "<i>«error»\nSessionBufferOverflow\nUnauthorizedKey\nInvalidPin\nInvalidCertificate\nInconsistentData\nInvalidCardSignature\nCardSignatureNotVerifiable\nSelectFile\nCrypto\nCryptoIO" as errors <<purple>>  {
        +val message: String
        +val cause: Any?
    }
    package "spi" as spi {
        +interface "AsymmetricCryptoCardTransactionManagerFactory" as AsymmetricCryptoCardTransactionManagerFactory <<red>> {
        }
        +interface "CaCertificateParser" as CaCertificateParser <<red>> {
        }
        +interface "CardCertificateParser" as CardCertificateParser <<red>> {
        }
        +interface "PcaCertificate" as PcaCertificate <<red>> {
        }
        +interface "CaCertificate" as CaCertificate <<red>> {
        }
        +interface "CardCertificate" as CardCertificate <<red>> {
        }
        +interface "SymmetricCryptoCardTransactionManagerFactory" as SymmetricCryptoCardTransactionManagerFactory <<red>> {
        }
        +interface "CardTransactionCryptoExtension" as CardTransactionCryptoExtension <<red>> {
        }
    }
}

}

' Associations

TransactionManager .up.> SelectFileControl #C_USE : use >
TransactionManager .up.> GetDataTag #C_USE : use >
TransactionManager .up.> PutDataTag #C_USE : use >
TransactionManager .right.> SearchCommandData #C_USE : use >
TransactionManager .right.> SecureSessionStatus #C_LINK : provide >

SecureTransactionManager .....> CardTransactionCryptoExtension #C_LINK : provide >

SecureSymmetricCryptoTransactionManager .up.> WriteAccessLevel #C_USE : use >
SecureSymmetricCryptoTransactionManager .right.> SvOperation #C_USE : use >
SecureSymmetricCryptoTransactionManager .right.> SvAction #C_USE : use >

SymmetricCryptoSecuritySetting ..> WriteAccessLevel #C_USE : use >

AsymmetricCryptoSecuritySetting .up.> PcaCertificate #C_USE : use >
AsymmetricCryptoSecuritySetting .up.> CaCertificate #C_USE : use >
AsymmetricCryptoSecuritySetting .up.> CaCertificateParser #C_USE : use >
AsymmetricCryptoSecuritySetting .up.> CardCertificateParser #C_USE : use >

SecureSessionStatus ..> WriteAccessLevel #C_LINK : provide >
SecureSessionStatus ..> SecureSessionType #C_LINK : provide >

CalypsoCardSelectionExtension .up.> SelectFileControl #C_USE : use >
CalypsoCardSelectionExtension .up.> GetDataTag #C_USE : use >
CalypsoCardSelectionExtension .up.> WriteAccessLevel #C_USE : use >

CalypsoCard ..> DirectoryHeader #C_LINK : provide >
CalypsoCard ..> ElementaryFile #C_LINK : provide >
CalypsoCard +-right- CardProductType
CalypsoCard .right.> CardProductType #C_LINK : provide >
CalypsoCard ..> SvLoadLogRecord #C_LINK : provide >
CalypsoCard ..> SvDebitLogRecord #C_LINK : provide >

DirectoryHeader ..> WriteAccessLevel #C_USE : use >

ElementaryFile +-- FileType
ElementaryFile ...> FileHeader #C_LINK : provide >
ElementaryFile ...> FileData #C_LINK : provide >

FileHeader .up.> FileType #C_LINK : provide >

' == LAYOUT ==

'SymmetricCryptoSecuritySetting -[hidden]- AsymmetricCryptoSecuritySetting
AsymmetricCryptoSecuritySetting -[hidden]left- errors

AsymmetricCryptoCardTransactionManagerFactory -[hidden]- PcaCertificate
PcaCertificate -[hidden]right- CaCertificate
CaCertificate -[hidden]right- CardCertificate
CardCertificate -[hidden]right- CaCertificateParser
CaCertificateParser -[hidden]right- CardCertificateParser

' == STYLE ==

package calypsoCard #C_GREY1 {}
package calypsoCard.card #C_GREY2 {}
package calypsoCard.transaction #C_GREY2 {}
package calypsoCard.transaction.spi #C_GREY3 {}

@enduml