@startuml
title
    <img:../assets/logo.svg{scale=0.2}>

    AsymmetricSecuritySetting (2024-02-16)
end title

participant "App" as app
participant "AsymmetricSecuritySetting" as setting
participant "PcaCertificate" as pca
participant "CaCertificate" as ca

== addPcaCertificate ==

activate app

app -> setting : addPcaCertificate (pcaCertificate)
activate setting

setting -> pca : checkCertificateAndGetContent ()
activate pca
setting <-- pca : caCertificateContentSpi
deactivate pca

setting -> setting : saveCaCertificateContent (caCertificateContentSpi)
note right
    map.put(caCertificateContentSpi.getPublicKeyReference(), caCertificateContentSpi)
end note

app <-- setting
deactivate setting

== addCaCertificate ==

app -> setting : addCaCertificate (caCertificate)
activate setting

setting -> ca : getIssuerPublicKeyReference ()
activate ca
setting <-- ca : issuerPublicKeyReference
deactivate ca

setting -> setting : issuerCaCertificateContentSpi := findCaCertificateContentSpi (issuerPublicKeyReference)

setting -> ca : checkCertificateAndGetContent (issuerCaCertificateContentSpi)
activate ca
setting <-- ca : caCertificateContentSpi
deactivate ca

setting -> setting : saveCaCertificateContent (caCertificateContentSpi)
note right
    map.put(caCertificateContentSpi.getPublicKeyReference(), caCertificateContentSpi)
end note

app <-- setting
deactivate setting


@enduml