@startuml
title
    <img:../assets/logo.svg{scale=0.2}>

    AsymmetricSecuritySetting (2024-01-23)
end title

participant "App" as app
participant "AsymmetricSecuritySetting" as setting
participant "PcaCertificate" as pca
participant "CaCertificate" as ca

== addPcaCertificate ==

activate app

app -> setting : addPcaCertificate (pcaCertificate)
activate setting

setting -> pca : getPublicKey ()
activate pca
setting <-- pca : publicKeySpi
deactivate pca

setting -> setting : savePublicKey (publicKeySpi)
note right
    map.put(publicKeySpi.getReference(), publicKeySpi.getValue())
end note

app <-- setting
deactivate setting

== addCaCertificate ==

app -> setting : addCaCertificate (caCertificate)
activate setting

setting -> ca : getIssuerPublicKeyReference ()
activate ca
setting <-- ca : issuerPublicKeyReference
deactivate ca

setting -> setting : issuerPublicKey := findPublicKey (issuerPublicKeyReference)

setting -> ca : getPublicKey (issuerPublicKey.getPublicKey ())
activate ca
setting <-- ca : publicKeySpi
deactivate ca

setting -> setting : savePublicKey (publicKeySpi)
note right
    map.put(publicKeySpi.getReference(), publicKeySpi.getValue())
end note

app <-- setting
deactivate setting


@enduml